export default {
    "1": "We get together",
    "9": "Our first \"Long Distance Relationship\" phone call",
    "21": "The first time you fly to see me",
    "22": "The first time we get beers with Mel and her friend Sonya and they tell me you're a keeper",
    "39": "the first reminder I set to ask a friend about a connection of theirs in Minneapolis",
    "67": "The first time I fly to see you in Minneapolis",
    "100": "My first Eyeo, your notable 103 degree fever",
    "139": "Our first time going to a wedding together <3",
    "143": "The beginning of you spending a full month in NYC",
    "186": "The beginning of me spending a full month living in your house",
    "202": "My wisdom tooth is heinously extracted; you buy me pink flowers. Shortly afterward those flowers become my phone background.",
    "207": "We watch the bachelorette with Monty and Drake",
    "254": "We go to that strange event in the creepy warehouse in bushwick where we're asked to be a little too vulnerable in the wrong way.",
    "293": "Even though we're miles apart, we toast to celebrate your first completed semester of grad school. I brag to everyone I know about it and tell work I'll be logging off early.",
    "307": "We do Chanukah with my family",
    "308": "We go disco dancing with your mom",
    "309": "We spend 7 hours on an Amtrak with Molly and Nora to go see Al",
    "311": "You're my New Years kiss, Al is also your New Years kiss",
    "312": " I don't fly home after New Years, I fly to your home. We get incoherently confused about whether we're flying out of DC or Virginia.",
    "315": "Our first time trying to cross country ski together",
    "322": "We celebrate your birthday together. I get to see all your friends at once and I can't stop smiling at how much they all love you",
    "323": "When I leave Minneapolis, your housemates tell me they'll miss me and remind me that we've spent all of 2020 together. We've officially decided that I'll move to you when my lease is up.",
    "356": "You come to town on Valentine's Day and we thought we wouldn't care but we really do. We cuddle the whole weekend and pee with the door open",
    "357": "You meet my band. We have dinner for 3 hours and then jam while you draw.",
    "365": "Our 1 year Anniversary. One full year of Julia."
};